name: main
on: 
  push:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.7'
      - run: pwd
      - run: ls -l
      - run: git branch
      - run: go mod tidy
      - run: make test

  build_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: echo "Build container"
      - run: gcloud info
      - run: gcloud builds submit --tag gcr.io/k8s-pilot-323307/go-test:latest .
